# Generated by Django 4.1.6 on 2023-03-26 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad_Mes',
            fields=[
                ('ciudad_mes_id', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField()),
                ('ciudad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.ciudad')),
            ],
        ),
    ]
