# Generated by Django 4.1.6 on 2023-03-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0002_ciudad_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='mejor_epoca',
        ),
    ]
