# Generated by Django 4.1.6 on 2023-03-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_remove_ciudad_mejor_epoca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudad_mes',
            old_name='ciudad_id',
            new_name='ciudad',
        ),
    ]
