# Generated by Django 4.1.6 on 2023-03-31 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0005_ciudad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad_image',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Imagenes', to='Gestion.ciudad'),
        ),
        migrations.AlterField(
            model_name='ciudad_mes',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Meses', to='Gestion.ciudad'),
        ),
    ]
