# Generated by Django 4.1.6 on 2023-04-04 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gestion', '0006_alter_ciudad_image_ciudad_alter_ciudad_mes_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes_Toast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_cabecera', models.CharField(max_length=255)),
                ('mensaje_detalle', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toasts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
