# Generated by Django 4.1.6 on 2023-03-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sesion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
