# Generated by Django 4.1.6 on 2023-03-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sesion', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(default=None, upload_to='image/'),
        ),
    ]
