# Generated by Django 4.1.6 on 2023-03-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sesion', '0005_alter_image_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='image',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
